name: Deploy with Terraform and Ansible

on:
  push:
    branches:
      - sample
  workflow_dispatch:

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    outputs:
      ec2_ip: ${{ steps.get_ec2_ip.outputs.ec2_ip }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: terraform apply -auto-approve

      - name: Get EC2 public IP
        id: get_ec2_ip
        run: |
          RAW_OUTPUT=$(terraform output -raw ec2_user_public_ip 2>/dev/null)
          CLEAN_IP=$(echo "$RAW_OUTPUT" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')

          if [ -z "$CLEAN_IP" ]; then
            echo "Failed to get a valid IP address"
            exit 1
          fi

          echo "ec2_ip=$CLEAN_IP" >> "$GITHUB_OUTPUT"
          echo "EC2 IP found: $CLEAN_IP"

  ansible_deploy:
    runs-on: ubuntu-latest
    needs: terraform_apply

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa_github_actions_new
          chmod 600 ~/.ssh/id_rsa_github_actions_new

      - name: Generate dynamic inventory.ini
        run: |
          echo "[app]" > inventory.ini
          echo "${{ needs.terraform_apply.outputs.ec2_ip }} ansible_user=ec2-user ansible_ssh_private_key_file=/home/runner/.ssh/id_rsa_github_actions_new" >> inventory.ini

      - name: Add EC2 hosts to known_hosts
        run: |
          ssh-keyscan -H ${{ needs.terraform_apply.outputs.ec2_ip }} >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: ansible-playbook -i inventory.ini playbook.yml --private-key /home/runner/.ssh/id_rsa_github_actions_new
